export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY"
export const HANDLE_DROPDOWN_CART = "HANDLE_DROPDOWN_CART"
export const HANDLE_CURRENCY = "HANDLE_CURRENCY"